namespace Project_ACS
{
    partial class MainMenu_Master
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainMenu_Master));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel1 = new System.Windows.Forms.Panel();
            this.label2 = new System.Windows.Forms.Label();
            this.lbl_nama = new System.Windows.Forms.Label();
            this.panel2 = new System.Windows.Forms.Panel();
            this.pl_submenu_master = new System.Windows.Forms.Panel();
            this.btn_master_bp = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_master_akun = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_master_warehouse = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pl_submenu_barang = new System.Windows.Forms.Panel();
            this.btn_inventory_merk = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_inventory_kategori = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_inventory_barang = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_master_inventory = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_master = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_dashboard = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pl_logo = new System.Windows.Forms.Panel();
            this.pl_main = new System.Windows.Forms.Panel();
            this.panel1.SuspendLayout();
            this.panel2.SuspendLayout();
            this.pl_submenu_master.SuspendLayout();
            this.pl_submenu_barang.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(44)))));
            this.panel1.Controls.Add(this.label2);
            this.panel1.Controls.Add(this.lbl_nama);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(200, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(864, 70);
            this.panel1.TabIndex = 8;
            // 
            // label2
            // 
            this.label2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label2.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(220)))), ((int)(((byte)(228)))));
            this.label2.Location = new System.Drawing.Point(610, 32);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(251, 23);
            this.label2.TabIndex = 8;
            this.label2.Text = "Master Account";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // lbl_nama
            // 
            this.lbl_nama.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.lbl_nama.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbl_nama.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(220)))), ((int)(((byte)(228)))));
            this.lbl_nama.Location = new System.Drawing.Point(610, 9);
            this.lbl_nama.Name = "lbl_nama";
            this.lbl_nama.Size = new System.Drawing.Size(251, 23);
            this.lbl_nama.TabIndex = 7;
            this.lbl_nama.Text = "Welcome, User";
            this.lbl_nama.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(44)))));
            this.panel2.Controls.Add(this.pl_submenu_master);
            this.panel2.Controls.Add(this.btn_master);
            this.panel2.Controls.Add(this.btn_dashboard);
            this.panel2.Controls.Add(this.pl_logo);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel2.Location = new System.Drawing.Point(0, 0);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(200, 601);
            this.panel2.TabIndex = 7;
            // 
            // pl_submenu_master
            // 
            this.pl_submenu_master.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.pl_submenu_master.Controls.Add(this.btn_master_bp);
            this.pl_submenu_master.Controls.Add(this.btn_master_akun);
            this.pl_submenu_master.Controls.Add(this.btn_master_warehouse);
            this.pl_submenu_master.Controls.Add(this.pl_submenu_barang);
            this.pl_submenu_master.Controls.Add(this.btn_master_inventory);
            this.pl_submenu_master.Dock = System.Windows.Forms.DockStyle.Top;
            this.pl_submenu_master.Location = new System.Drawing.Point(0, 182);
            this.pl_submenu_master.MaximumSize = new System.Drawing.Size(0, 240);
            this.pl_submenu_master.MinimumSize = new System.Drawing.Size(200, 0);
            this.pl_submenu_master.Name = "pl_submenu_master";
            this.pl_submenu_master.Size = new System.Drawing.Size(200, 240);
            this.pl_submenu_master.TabIndex = 7;
            this.pl_submenu_master.Tag = "-1";
            // 
            // btn_master_bp
            // 
            this.btn_master_bp.AllowAnimations = true;
            this.btn_master_bp.AllowMouseEffects = true;
            this.btn_master_bp.AllowToggling = false;
            this.btn_master_bp.AnimationSpeed = 200;
            this.btn_master_bp.AutoGenerateColors = false;
            this.btn_master_bp.AutoRoundBorders = false;
            this.btn_master_bp.AutoSizeLeftIcon = true;
            this.btn_master_bp.AutoSizeRightIcon = true;
            this.btn_master_bp.BackColor = System.Drawing.Color.Transparent;
            this.btn_master_bp.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.btn_master_bp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_master_bp.BackgroundImage")));
            this.btn_master_bp.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master_bp.ButtonText = "Business Partner";
            this.btn_master_bp.ButtonTextMarginLeft = 0;
            this.btn_master_bp.ColorContrastOnClick = 45;
            this.btn_master_bp.ColorContrastOnHover = 45;
            this.btn_master_bp.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_master_bp.CustomizableEdges = borderEdges1;
            this.btn_master_bp.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_master_bp.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_master_bp.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_master_bp.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_master_bp.Dock = System.Windows.Forms.DockStyle.Top;
            this.btn_master_bp.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btn_master_bp.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_master_bp.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(220)))), ((int)(((byte)(228)))));
            this.btn_master_bp.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_master_bp.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_master_bp.IconLeftPadding = new System.Windows.Forms.Padding(22, 3, 3, 3);
            this.btn_master_bp.IconMarginLeft = 11;
            this.btn_master_bp.IconPadding = 10;
            this.btn_master_bp.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_master_bp.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_master_bp.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_master_bp.IconSize = 25;
            this.btn_master_bp.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_master_bp.IdleBorderRadius = 1;
            this.btn_master_bp.IdleBorderThickness = 1;
            this.btn_master_bp.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.btn_master_bp.IdleIconLeftImage = global::Project_ACS.res_icons.briefcase_solid;
            this.btn_master_bp.IdleIconRightImage = null;
            this.btn_master_bp.IndicateFocus = false;
            this.btn_master_bp.Location = new System.Drawing.Point(0, 237);
            this.btn_master_bp.Name = "btn_master_bp";
            this.btn_master_bp.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_master_bp.OnDisabledState.BorderRadius = 0;
            this.btn_master_bp.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master_bp.OnDisabledState.BorderThickness = 0;
            this.btn_master_bp.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_master_bp.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_master_bp.OnDisabledState.IconLeftImage = null;
            this.btn_master_bp.OnDisabledState.IconRightImage = null;
            this.btn_master_bp.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btn_master_bp.onHoverState.BorderRadius = 0;
            this.btn_master_bp.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master_bp.onHoverState.BorderThickness = 0;
            this.btn_master_bp.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(96)))));
            this.btn_master_bp.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_master_bp.onHoverState.IconLeftImage = null;
            this.btn_master_bp.onHoverState.IconRightImage = null;
            this.btn_master_bp.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_master_bp.OnIdleState.BorderRadius = 0;
            this.btn_master_bp.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master_bp.OnIdleState.BorderThickness = 0;
            this.btn_master_bp.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.btn_master_bp.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(220)))), ((int)(((byte)(228)))));
            this.btn_master_bp.OnIdleState.IconLeftImage = global::Project_ACS.res_icons.briefcase_solid;
            this.btn_master_bp.OnIdleState.IconRightImage = null;
            this.btn_master_bp.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.btn_master_bp.OnPressedState.BorderRadius = 0;
            this.btn_master_bp.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master_bp.OnPressedState.BorderThickness = 0;
            this.btn_master_bp.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(34)))));
            this.btn_master_bp.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_master_bp.OnPressedState.IconLeftImage = null;
            this.btn_master_bp.OnPressedState.IconRightImage = null;
            this.btn_master_bp.Size = new System.Drawing.Size(200, 39);
            this.btn_master_bp.TabIndex = 35;
            this.btn_master_bp.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_master_bp.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_master_bp.TextMarginLeft = 0;
            this.btn_master_bp.TextPadding = new System.Windows.Forms.Padding(51, 0, 0, 0);
            this.btn_master_bp.UseDefaultRadiusAndThickness = true;
            // 
            // btn_master_akun
            // 
            this.btn_master_akun.AllowAnimations = true;
            this.btn_master_akun.AllowMouseEffects = true;
            this.btn_master_akun.AllowToggling = false;
            this.btn_master_akun.AnimationSpeed = 200;
            this.btn_master_akun.AutoGenerateColors = false;
            this.btn_master_akun.AutoRoundBorders = false;
            this.btn_master_akun.AutoSizeLeftIcon = true;
            this.btn_master_akun.AutoSizeRightIcon = true;
            this.btn_master_akun.BackColor = System.Drawing.Color.Transparent;
            this.btn_master_akun.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.btn_master_akun.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_master_akun.BackgroundImage")));
            this.btn_master_akun.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master_akun.ButtonText = "Akun";
            this.btn_master_akun.ButtonTextMarginLeft = 0;
            this.btn_master_akun.ColorContrastOnClick = 45;
            this.btn_master_akun.ColorContrastOnHover = 45;
            this.btn_master_akun.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_master_akun.CustomizableEdges = borderEdges2;
            this.btn_master_akun.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_master_akun.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_master_akun.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_master_akun.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_master_akun.Dock = System.Windows.Forms.DockStyle.Top;
            this.btn_master_akun.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btn_master_akun.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_master_akun.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(220)))), ((int)(((byte)(228)))));
            this.btn_master_akun.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_master_akun.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_master_akun.IconLeftPadding = new System.Windows.Forms.Padding(22, 3, 3, 3);
            this.btn_master_akun.IconMarginLeft = 11;
            this.btn_master_akun.IconPadding = 10;
            this.btn_master_akun.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_master_akun.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_master_akun.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_master_akun.IconSize = 25;
            this.btn_master_akun.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_master_akun.IdleBorderRadius = 1;
            this.btn_master_akun.IdleBorderThickness = 1;
            this.btn_master_akun.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.btn_master_akun.IdleIconLeftImage = global::Project_ACS.res_icons.user_solid;
            this.btn_master_akun.IdleIconRightImage = null;
            this.btn_master_akun.IndicateFocus = false;
            this.btn_master_akun.Location = new System.Drawing.Point(0, 198);
            this.btn_master_akun.Name = "btn_master_akun";
            this.btn_master_akun.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_master_akun.OnDisabledState.BorderRadius = 1;
            this.btn_master_akun.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master_akun.OnDisabledState.BorderThickness = 1;
            this.btn_master_akun.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_master_akun.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_master_akun.OnDisabledState.IconLeftImage = null;
            this.btn_master_akun.OnDisabledState.IconRightImage = null;
            this.btn_master_akun.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btn_master_akun.onHoverState.BorderRadius = 1;
            this.btn_master_akun.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master_akun.onHoverState.BorderThickness = 1;
            this.btn_master_akun.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(96)))));
            this.btn_master_akun.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_master_akun.onHoverState.IconLeftImage = null;
            this.btn_master_akun.onHoverState.IconRightImage = null;
            this.btn_master_akun.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_master_akun.OnIdleState.BorderRadius = 1;
            this.btn_master_akun.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master_akun.OnIdleState.BorderThickness = 1;
            this.btn_master_akun.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.btn_master_akun.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(220)))), ((int)(((byte)(228)))));
            this.btn_master_akun.OnIdleState.IconLeftImage = global::Project_ACS.res_icons.user_solid;
            this.btn_master_akun.OnIdleState.IconRightImage = null;
            this.btn_master_akun.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.btn_master_akun.OnPressedState.BorderRadius = 1;
            this.btn_master_akun.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master_akun.OnPressedState.BorderThickness = 1;
            this.btn_master_akun.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(34)))));
            this.btn_master_akun.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_master_akun.OnPressedState.IconLeftImage = null;
            this.btn_master_akun.OnPressedState.IconRightImage = null;
            this.btn_master_akun.Size = new System.Drawing.Size(200, 39);
            this.btn_master_akun.TabIndex = 34;
            this.btn_master_akun.Tag = "5";
            this.btn_master_akun.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_master_akun.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_master_akun.TextMarginLeft = 0;
            this.btn_master_akun.TextPadding = new System.Windows.Forms.Padding(51, 0, 0, 0);
            this.btn_master_akun.UseDefaultRadiusAndThickness = true;
            this.btn_master_akun.Click += new System.EventHandler(this.buttonPress);
            // 
            // btn_master_warehouse
            // 
            this.btn_master_warehouse.AllowAnimations = true;
            this.btn_master_warehouse.AllowMouseEffects = true;
            this.btn_master_warehouse.AllowToggling = false;
            this.btn_master_warehouse.AnimationSpeed = 200;
            this.btn_master_warehouse.AutoGenerateColors = false;
            this.btn_master_warehouse.AutoRoundBorders = false;
            this.btn_master_warehouse.AutoSizeLeftIcon = true;
            this.btn_master_warehouse.AutoSizeRightIcon = true;
            this.btn_master_warehouse.BackColor = System.Drawing.Color.Transparent;
            this.btn_master_warehouse.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.btn_master_warehouse.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_master_warehouse.BackgroundImage")));
            this.btn_master_warehouse.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master_warehouse.ButtonText = "Warehouse";
            this.btn_master_warehouse.ButtonTextMarginLeft = 0;
            this.btn_master_warehouse.ColorContrastOnClick = 45;
            this.btn_master_warehouse.ColorContrastOnHover = 45;
            this.btn_master_warehouse.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btn_master_warehouse.CustomizableEdges = borderEdges3;
            this.btn_master_warehouse.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_master_warehouse.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_master_warehouse.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_master_warehouse.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_master_warehouse.Dock = System.Windows.Forms.DockStyle.Top;
            this.btn_master_warehouse.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btn_master_warehouse.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_master_warehouse.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(220)))), ((int)(((byte)(228)))));
            this.btn_master_warehouse.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_master_warehouse.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_master_warehouse.IconLeftPadding = new System.Windows.Forms.Padding(22, 3, 3, 3);
            this.btn_master_warehouse.IconMarginLeft = 11;
            this.btn_master_warehouse.IconPadding = 10;
            this.btn_master_warehouse.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_master_warehouse.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_master_warehouse.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_master_warehouse.IconSize = 25;
            this.btn_master_warehouse.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_master_warehouse.IdleBorderRadius = 1;
            this.btn_master_warehouse.IdleBorderThickness = 1;
            this.btn_master_warehouse.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.btn_master_warehouse.IdleIconLeftImage = global::Project_ACS.res_icons.warehouse_solid;
            this.btn_master_warehouse.IdleIconRightImage = null;
            this.btn_master_warehouse.IndicateFocus = false;
            this.btn_master_warehouse.Location = new System.Drawing.Point(0, 159);
            this.btn_master_warehouse.Name = "btn_master_warehouse";
            this.btn_master_warehouse.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_master_warehouse.OnDisabledState.BorderRadius = 1;
            this.btn_master_warehouse.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master_warehouse.OnDisabledState.BorderThickness = 1;
            this.btn_master_warehouse.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_master_warehouse.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_master_warehouse.OnDisabledState.IconLeftImage = null;
            this.btn_master_warehouse.OnDisabledState.IconRightImage = null;
            this.btn_master_warehouse.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btn_master_warehouse.onHoverState.BorderRadius = 1;
            this.btn_master_warehouse.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master_warehouse.onHoverState.BorderThickness = 1;
            this.btn_master_warehouse.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(96)))));
            this.btn_master_warehouse.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_master_warehouse.onHoverState.IconLeftImage = null;
            this.btn_master_warehouse.onHoverState.IconRightImage = null;
            this.btn_master_warehouse.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_master_warehouse.OnIdleState.BorderRadius = 1;
            this.btn_master_warehouse.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master_warehouse.OnIdleState.BorderThickness = 1;
            this.btn_master_warehouse.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.btn_master_warehouse.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(220)))), ((int)(((byte)(228)))));
            this.btn_master_warehouse.OnIdleState.IconLeftImage = global::Project_ACS.res_icons.warehouse_solid;
            this.btn_master_warehouse.OnIdleState.IconRightImage = null;
            this.btn_master_warehouse.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.btn_master_warehouse.OnPressedState.BorderRadius = 1;
            this.btn_master_warehouse.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master_warehouse.OnPressedState.BorderThickness = 1;
            this.btn_master_warehouse.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(34)))));
            this.btn_master_warehouse.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_master_warehouse.OnPressedState.IconLeftImage = null;
            this.btn_master_warehouse.OnPressedState.IconRightImage = null;
            this.btn_master_warehouse.Size = new System.Drawing.Size(200, 39);
            this.btn_master_warehouse.TabIndex = 33;
            this.btn_master_warehouse.Tag = "4";
            this.btn_master_warehouse.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_master_warehouse.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_master_warehouse.TextMarginLeft = 0;
            this.btn_master_warehouse.TextPadding = new System.Windows.Forms.Padding(51, 0, 0, 0);
            this.btn_master_warehouse.UseDefaultRadiusAndThickness = true;
            this.btn_master_warehouse.Click += new System.EventHandler(this.buttonPress);
            // 
            // pl_submenu_barang
            // 
            this.pl_submenu_barang.Controls.Add(this.btn_inventory_merk);
            this.pl_submenu_barang.Controls.Add(this.btn_inventory_kategori);
            this.pl_submenu_barang.Controls.Add(this.btn_inventory_barang);
            this.pl_submenu_barang.Dock = System.Windows.Forms.DockStyle.Top;
            this.pl_submenu_barang.Location = new System.Drawing.Point(0, 39);
            this.pl_submenu_barang.MaximumSize = new System.Drawing.Size(200, 120);
            this.pl_submenu_barang.Name = "pl_submenu_barang";
            this.pl_submenu_barang.Size = new System.Drawing.Size(200, 120);
            this.pl_submenu_barang.TabIndex = 7;
            this.pl_submenu_barang.Tag = "-1";
            // 
            // btn_inventory_merk
            // 
            this.btn_inventory_merk.AllowAnimations = true;
            this.btn_inventory_merk.AllowMouseEffects = true;
            this.btn_inventory_merk.AllowToggling = false;
            this.btn_inventory_merk.AnimationSpeed = 200;
            this.btn_inventory_merk.AutoGenerateColors = false;
            this.btn_inventory_merk.AutoRoundBorders = false;
            this.btn_inventory_merk.AutoSizeLeftIcon = true;
            this.btn_inventory_merk.AutoSizeRightIcon = true;
            this.btn_inventory_merk.BackColor = System.Drawing.Color.Transparent;
            this.btn_inventory_merk.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.btn_inventory_merk.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_inventory_merk.BackgroundImage")));
            this.btn_inventory_merk.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_inventory_merk.ButtonText = "Merk";
            this.btn_inventory_merk.ButtonTextMarginLeft = 0;
            this.btn_inventory_merk.ColorContrastOnClick = 45;
            this.btn_inventory_merk.ColorContrastOnHover = 45;
            this.btn_inventory_merk.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btn_inventory_merk.CustomizableEdges = borderEdges4;
            this.btn_inventory_merk.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_inventory_merk.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_inventory_merk.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_inventory_merk.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_inventory_merk.Dock = System.Windows.Forms.DockStyle.Top;
            this.btn_inventory_merk.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btn_inventory_merk.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_inventory_merk.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(220)))), ((int)(((byte)(228)))));
            this.btn_inventory_merk.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_inventory_merk.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_inventory_merk.IconLeftPadding = new System.Windows.Forms.Padding(35, 3, 3, 3);
            this.btn_inventory_merk.IconMarginLeft = 11;
            this.btn_inventory_merk.IconPadding = 10;
            this.btn_inventory_merk.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_inventory_merk.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_inventory_merk.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_inventory_merk.IconSize = 25;
            this.btn_inventory_merk.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_inventory_merk.IdleBorderRadius = 1;
            this.btn_inventory_merk.IdleBorderThickness = 1;
            this.btn_inventory_merk.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.btn_inventory_merk.IdleIconLeftImage = global::Project_ACS.res_icons.copyright_solid;
            this.btn_inventory_merk.IdleIconRightImage = null;
            this.btn_inventory_merk.IndicateFocus = false;
            this.btn_inventory_merk.Location = new System.Drawing.Point(0, 78);
            this.btn_inventory_merk.Name = "btn_inventory_merk";
            this.btn_inventory_merk.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_inventory_merk.OnDisabledState.BorderRadius = 1;
            this.btn_inventory_merk.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_inventory_merk.OnDisabledState.BorderThickness = 1;
            this.btn_inventory_merk.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_inventory_merk.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_inventory_merk.OnDisabledState.IconLeftImage = null;
            this.btn_inventory_merk.OnDisabledState.IconRightImage = null;
            this.btn_inventory_merk.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btn_inventory_merk.onHoverState.BorderRadius = 1;
            this.btn_inventory_merk.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_inventory_merk.onHoverState.BorderThickness = 1;
            this.btn_inventory_merk.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(96)))));
            this.btn_inventory_merk.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_inventory_merk.onHoverState.IconLeftImage = null;
            this.btn_inventory_merk.onHoverState.IconRightImage = null;
            this.btn_inventory_merk.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_inventory_merk.OnIdleState.BorderRadius = 1;
            this.btn_inventory_merk.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_inventory_merk.OnIdleState.BorderThickness = 1;
            this.btn_inventory_merk.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.btn_inventory_merk.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(220)))), ((int)(((byte)(228)))));
            this.btn_inventory_merk.OnIdleState.IconLeftImage = global::Project_ACS.res_icons.copyright_solid;
            this.btn_inventory_merk.OnIdleState.IconRightImage = null;
            this.btn_inventory_merk.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.btn_inventory_merk.OnPressedState.BorderRadius = 1;
            this.btn_inventory_merk.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_inventory_merk.OnPressedState.BorderThickness = 1;
            this.btn_inventory_merk.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(34)))));
            this.btn_inventory_merk.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_inventory_merk.OnPressedState.IconLeftImage = null;
            this.btn_inventory_merk.OnPressedState.IconRightImage = null;
            this.btn_inventory_merk.Size = new System.Drawing.Size(200, 39);
            this.btn_inventory_merk.TabIndex = 30;
            this.btn_inventory_merk.Tag = "3";
            this.btn_inventory_merk.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_inventory_merk.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_inventory_merk.TextMarginLeft = 0;
            this.btn_inventory_merk.TextPadding = new System.Windows.Forms.Padding(64, 0, 0, 0);
            this.btn_inventory_merk.UseDefaultRadiusAndThickness = true;
            this.btn_inventory_merk.Click += new System.EventHandler(this.buttonPress);
            // 
            // btn_inventory_kategori
            // 
            this.btn_inventory_kategori.AllowAnimations = true;
            this.btn_inventory_kategori.AllowMouseEffects = true;
            this.btn_inventory_kategori.AllowToggling = false;
            this.btn_inventory_kategori.AnimationSpeed = 200;
            this.btn_inventory_kategori.AutoGenerateColors = false;
            this.btn_inventory_kategori.AutoRoundBorders = false;
            this.btn_inventory_kategori.AutoSizeLeftIcon = true;
            this.btn_inventory_kategori.AutoSizeRightIcon = true;
            this.btn_inventory_kategori.BackColor = System.Drawing.Color.Transparent;
            this.btn_inventory_kategori.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.btn_inventory_kategori.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_inventory_kategori.BackgroundImage")));
            this.btn_inventory_kategori.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_inventory_kategori.ButtonText = "Kategori";
            this.btn_inventory_kategori.ButtonTextMarginLeft = 0;
            this.btn_inventory_kategori.ColorContrastOnClick = 45;
            this.btn_inventory_kategori.ColorContrastOnHover = 45;
            this.btn_inventory_kategori.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btn_inventory_kategori.CustomizableEdges = borderEdges5;
            this.btn_inventory_kategori.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_inventory_kategori.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_inventory_kategori.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_inventory_kategori.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_inventory_kategori.Dock = System.Windows.Forms.DockStyle.Top;
            this.btn_inventory_kategori.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btn_inventory_kategori.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_inventory_kategori.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(220)))), ((int)(((byte)(228)))));
            this.btn_inventory_kategori.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_inventory_kategori.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_inventory_kategori.IconLeftPadding = new System.Windows.Forms.Padding(35, 3, 3, 3);
            this.btn_inventory_kategori.IconMarginLeft = 11;
            this.btn_inventory_kategori.IconPadding = 10;
            this.btn_inventory_kategori.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_inventory_kategori.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_inventory_kategori.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_inventory_kategori.IconSize = 25;
            this.btn_inventory_kategori.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_inventory_kategori.IdleBorderRadius = 1;
            this.btn_inventory_kategori.IdleBorderThickness = 1;
            this.btn_inventory_kategori.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.btn_inventory_kategori.IdleIconLeftImage = global::Project_ACS.res_icons.code_branch_solid;
            this.btn_inventory_kategori.IdleIconRightImage = null;
            this.btn_inventory_kategori.IndicateFocus = false;
            this.btn_inventory_kategori.Location = new System.Drawing.Point(0, 39);
            this.btn_inventory_kategori.Name = "btn_inventory_kategori";
            this.btn_inventory_kategori.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_inventory_kategori.OnDisabledState.BorderRadius = 1;
            this.btn_inventory_kategori.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_inventory_kategori.OnDisabledState.BorderThickness = 1;
            this.btn_inventory_kategori.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_inventory_kategori.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_inventory_kategori.OnDisabledState.IconLeftImage = null;
            this.btn_inventory_kategori.OnDisabledState.IconRightImage = null;
            this.btn_inventory_kategori.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btn_inventory_kategori.onHoverState.BorderRadius = 1;
            this.btn_inventory_kategori.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_inventory_kategori.onHoverState.BorderThickness = 1;
            this.btn_inventory_kategori.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(96)))));
            this.btn_inventory_kategori.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_inventory_kategori.onHoverState.IconLeftImage = null;
            this.btn_inventory_kategori.onHoverState.IconRightImage = null;
            this.btn_inventory_kategori.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_inventory_kategori.OnIdleState.BorderRadius = 1;
            this.btn_inventory_kategori.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_inventory_kategori.OnIdleState.BorderThickness = 1;
            this.btn_inventory_kategori.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.btn_inventory_kategori.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(220)))), ((int)(((byte)(228)))));
            this.btn_inventory_kategori.OnIdleState.IconLeftImage = global::Project_ACS.res_icons.code_branch_solid;
            this.btn_inventory_kategori.OnIdleState.IconRightImage = null;
            this.btn_inventory_kategori.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.btn_inventory_kategori.OnPressedState.BorderRadius = 1;
            this.btn_inventory_kategori.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_inventory_kategori.OnPressedState.BorderThickness = 1;
            this.btn_inventory_kategori.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(34)))));
            this.btn_inventory_kategori.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_inventory_kategori.OnPressedState.IconLeftImage = null;
            this.btn_inventory_kategori.OnPressedState.IconRightImage = null;
            this.btn_inventory_kategori.Size = new System.Drawing.Size(200, 39);
            this.btn_inventory_kategori.TabIndex = 29;
            this.btn_inventory_kategori.Tag = "2";
            this.btn_inventory_kategori.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_inventory_kategori.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_inventory_kategori.TextMarginLeft = 0;
            this.btn_inventory_kategori.TextPadding = new System.Windows.Forms.Padding(64, 0, 0, 0);
            this.btn_inventory_kategori.UseDefaultRadiusAndThickness = true;
            this.btn_inventory_kategori.Click += new System.EventHandler(this.buttonPress);
            // 
            // btn_inventory_barang
            // 
            this.btn_inventory_barang.AllowAnimations = true;
            this.btn_inventory_barang.AllowMouseEffects = true;
            this.btn_inventory_barang.AllowToggling = false;
            this.btn_inventory_barang.AnimationSpeed = 200;
            this.btn_inventory_barang.AutoGenerateColors = false;
            this.btn_inventory_barang.AutoRoundBorders = false;
            this.btn_inventory_barang.AutoSizeLeftIcon = true;
            this.btn_inventory_barang.AutoSizeRightIcon = true;
            this.btn_inventory_barang.BackColor = System.Drawing.Color.Transparent;
            this.btn_inventory_barang.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.btn_inventory_barang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_inventory_barang.BackgroundImage")));
            this.btn_inventory_barang.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_inventory_barang.ButtonText = "Barang";
            this.btn_inventory_barang.ButtonTextMarginLeft = 0;
            this.btn_inventory_barang.ColorContrastOnClick = 45;
            this.btn_inventory_barang.ColorContrastOnHover = 45;
            this.btn_inventory_barang.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btn_inventory_barang.CustomizableEdges = borderEdges6;
            this.btn_inventory_barang.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_inventory_barang.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_inventory_barang.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_inventory_barang.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_inventory_barang.Dock = System.Windows.Forms.DockStyle.Top;
            this.btn_inventory_barang.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btn_inventory_barang.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_inventory_barang.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(220)))), ((int)(((byte)(228)))));
            this.btn_inventory_barang.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_inventory_barang.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_inventory_barang.IconLeftPadding = new System.Windows.Forms.Padding(35, 3, 3, 3);
            this.btn_inventory_barang.IconMarginLeft = 11;
            this.btn_inventory_barang.IconPadding = 10;
            this.btn_inventory_barang.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_inventory_barang.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_inventory_barang.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_inventory_barang.IconSize = 25;
            this.btn_inventory_barang.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_inventory_barang.IdleBorderRadius = 1;
            this.btn_inventory_barang.IdleBorderThickness = 1;
            this.btn_inventory_barang.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.btn_inventory_barang.IdleIconLeftImage = global::Project_ACS.res_icons.box_solid;
            this.btn_inventory_barang.IdleIconRightImage = null;
            this.btn_inventory_barang.IndicateFocus = false;
            this.btn_inventory_barang.Location = new System.Drawing.Point(0, 0);
            this.btn_inventory_barang.Name = "btn_inventory_barang";
            this.btn_inventory_barang.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_inventory_barang.OnDisabledState.BorderRadius = 1;
            this.btn_inventory_barang.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_inventory_barang.OnDisabledState.BorderThickness = 1;
            this.btn_inventory_barang.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_inventory_barang.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_inventory_barang.OnDisabledState.IconLeftImage = null;
            this.btn_inventory_barang.OnDisabledState.IconRightImage = null;
            this.btn_inventory_barang.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btn_inventory_barang.onHoverState.BorderRadius = 1;
            this.btn_inventory_barang.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_inventory_barang.onHoverState.BorderThickness = 1;
            this.btn_inventory_barang.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(96)))));
            this.btn_inventory_barang.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_inventory_barang.onHoverState.IconLeftImage = null;
            this.btn_inventory_barang.onHoverState.IconRightImage = null;
            this.btn_inventory_barang.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_inventory_barang.OnIdleState.BorderRadius = 1;
            this.btn_inventory_barang.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_inventory_barang.OnIdleState.BorderThickness = 1;
            this.btn_inventory_barang.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.btn_inventory_barang.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(220)))), ((int)(((byte)(228)))));
            this.btn_inventory_barang.OnIdleState.IconLeftImage = global::Project_ACS.res_icons.box_solid;
            this.btn_inventory_barang.OnIdleState.IconRightImage = null;
            this.btn_inventory_barang.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.btn_inventory_barang.OnPressedState.BorderRadius = 1;
            this.btn_inventory_barang.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_inventory_barang.OnPressedState.BorderThickness = 1;
            this.btn_inventory_barang.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(34)))));
            this.btn_inventory_barang.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_inventory_barang.OnPressedState.IconLeftImage = null;
            this.btn_inventory_barang.OnPressedState.IconRightImage = null;
            this.btn_inventory_barang.Size = new System.Drawing.Size(200, 39);
            this.btn_inventory_barang.TabIndex = 28;
            this.btn_inventory_barang.Tag = "1";
            this.btn_inventory_barang.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_inventory_barang.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_inventory_barang.TextMarginLeft = 0;
            this.btn_inventory_barang.TextPadding = new System.Windows.Forms.Padding(64, 0, 0, 0);
            this.btn_inventory_barang.UseDefaultRadiusAndThickness = true;
            this.btn_inventory_barang.Click += new System.EventHandler(this.buttonPress);
            // 
            // btn_master_inventory
            // 
            this.btn_master_inventory.AllowAnimations = true;
            this.btn_master_inventory.AllowMouseEffects = true;
            this.btn_master_inventory.AllowToggling = false;
            this.btn_master_inventory.AnimationSpeed = 200;
            this.btn_master_inventory.AutoGenerateColors = false;
            this.btn_master_inventory.AutoRoundBorders = false;
            this.btn_master_inventory.AutoSizeLeftIcon = true;
            this.btn_master_inventory.AutoSizeRightIcon = true;
            this.btn_master_inventory.BackColor = System.Drawing.Color.Transparent;
            this.btn_master_inventory.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.btn_master_inventory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_master_inventory.BackgroundImage")));
            this.btn_master_inventory.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master_inventory.ButtonText = "Inventory";
            this.btn_master_inventory.ButtonTextMarginLeft = 0;
            this.btn_master_inventory.ColorContrastOnClick = 45;
            this.btn_master_inventory.ColorContrastOnHover = 45;
            this.btn_master_inventory.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btn_master_inventory.CustomizableEdges = borderEdges7;
            this.btn_master_inventory.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_master_inventory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_master_inventory.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_master_inventory.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_master_inventory.Dock = System.Windows.Forms.DockStyle.Top;
            this.btn_master_inventory.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btn_master_inventory.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_master_inventory.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(220)))), ((int)(((byte)(228)))));
            this.btn_master_inventory.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_master_inventory.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_master_inventory.IconLeftPadding = new System.Windows.Forms.Padding(22, 3, 3, 3);
            this.btn_master_inventory.IconMarginLeft = 11;
            this.btn_master_inventory.IconPadding = 10;
            this.btn_master_inventory.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_master_inventory.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_master_inventory.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 15, 3);
            this.btn_master_inventory.IconSize = 25;
            this.btn_master_inventory.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_master_inventory.IdleBorderRadius = 1;
            this.btn_master_inventory.IdleBorderThickness = 1;
            this.btn_master_inventory.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.btn_master_inventory.IdleIconLeftImage = global::Project_ACS.res_icons.boxes_solid;
            this.btn_master_inventory.IdleIconRightImage = global::Project_ACS.res_icons.caret_down_solid;
            this.btn_master_inventory.IndicateFocus = false;
            this.btn_master_inventory.Location = new System.Drawing.Point(0, 0);
            this.btn_master_inventory.Name = "btn_master_inventory";
            this.btn_master_inventory.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_master_inventory.OnDisabledState.BorderRadius = 1;
            this.btn_master_inventory.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master_inventory.OnDisabledState.BorderThickness = 1;
            this.btn_master_inventory.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_master_inventory.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_master_inventory.OnDisabledState.IconLeftImage = null;
            this.btn_master_inventory.OnDisabledState.IconRightImage = null;
            this.btn_master_inventory.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btn_master_inventory.onHoverState.BorderRadius = 1;
            this.btn_master_inventory.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master_inventory.onHoverState.BorderThickness = 1;
            this.btn_master_inventory.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(96)))));
            this.btn_master_inventory.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_master_inventory.onHoverState.IconLeftImage = null;
            this.btn_master_inventory.onHoverState.IconRightImage = null;
            this.btn_master_inventory.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_master_inventory.OnIdleState.BorderRadius = 1;
            this.btn_master_inventory.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master_inventory.OnIdleState.BorderThickness = 1;
            this.btn_master_inventory.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(46)))), ((int)(((byte)(63)))));
            this.btn_master_inventory.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(220)))), ((int)(((byte)(228)))));
            this.btn_master_inventory.OnIdleState.IconLeftImage = global::Project_ACS.res_icons.boxes_solid;
            this.btn_master_inventory.OnIdleState.IconRightImage = global::Project_ACS.res_icons.caret_down_solid;
            this.btn_master_inventory.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.btn_master_inventory.OnPressedState.BorderRadius = 1;
            this.btn_master_inventory.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master_inventory.OnPressedState.BorderThickness = 1;
            this.btn_master_inventory.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(34)))));
            this.btn_master_inventory.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_master_inventory.OnPressedState.IconLeftImage = null;
            this.btn_master_inventory.OnPressedState.IconRightImage = null;
            this.btn_master_inventory.Size = new System.Drawing.Size(200, 39);
            this.btn_master_inventory.TabIndex = 15;
            this.btn_master_inventory.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_master_inventory.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_master_inventory.TextMarginLeft = 0;
            this.btn_master_inventory.TextPadding = new System.Windows.Forms.Padding(51, 0, 0, 0);
            this.btn_master_inventory.UseDefaultRadiusAndThickness = true;
            this.btn_master_inventory.Click += new System.EventHandler(this.btn_master_inventory_Click);
            // 
            // btn_master
            // 
            this.btn_master.AllowAnimations = true;
            this.btn_master.AllowMouseEffects = true;
            this.btn_master.AllowToggling = false;
            this.btn_master.AnimationSpeed = 200;
            this.btn_master.AutoGenerateColors = false;
            this.btn_master.AutoRoundBorders = false;
            this.btn_master.AutoSizeLeftIcon = true;
            this.btn_master.AutoSizeRightIcon = true;
            this.btn_master.BackColor = System.Drawing.Color.Transparent;
            this.btn_master.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(44)))));
            this.btn_master.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_master.BackgroundImage")));
            this.btn_master.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master.ButtonText = "Master";
            this.btn_master.ButtonTextMarginLeft = 0;
            this.btn_master.ColorContrastOnClick = 45;
            this.btn_master.ColorContrastOnHover = 45;
            this.btn_master.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btn_master.CustomizableEdges = borderEdges8;
            this.btn_master.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_master.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_master.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_master.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_master.Dock = System.Windows.Forms.DockStyle.Top;
            this.btn_master.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btn_master.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_master.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(220)))), ((int)(((byte)(228)))));
            this.btn_master.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_master.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_master.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_master.IconMarginLeft = 11;
            this.btn_master.IconPadding = 10;
            this.btn_master.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_master.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_master.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 15, 3);
            this.btn_master.IconSize = 25;
            this.btn_master.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_master.IdleBorderRadius = 1;
            this.btn_master.IdleBorderThickness = 1;
            this.btn_master.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(44)))));
            this.btn_master.IdleIconLeftImage = global::Project_ACS.res_icons.key_solid;
            this.btn_master.IdleIconRightImage = global::Project_ACS.res_icons.caret_down_solid;
            this.btn_master.IndicateFocus = false;
            this.btn_master.Location = new System.Drawing.Point(0, 143);
            this.btn_master.Name = "btn_master";
            this.btn_master.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_master.OnDisabledState.BorderRadius = 1;
            this.btn_master.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master.OnDisabledState.BorderThickness = 1;
            this.btn_master.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_master.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_master.OnDisabledState.IconLeftImage = null;
            this.btn_master.OnDisabledState.IconRightImage = null;
            this.btn_master.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btn_master.onHoverState.BorderRadius = 1;
            this.btn_master.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master.onHoverState.BorderThickness = 1;
            this.btn_master.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(75)))));
            this.btn_master.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_master.onHoverState.IconLeftImage = null;
            this.btn_master.onHoverState.IconRightImage = null;
            this.btn_master.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_master.OnIdleState.BorderRadius = 1;
            this.btn_master.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master.OnIdleState.BorderThickness = 1;
            this.btn_master.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(44)))));
            this.btn_master.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(220)))), ((int)(((byte)(228)))));
            this.btn_master.OnIdleState.IconLeftImage = global::Project_ACS.res_icons.key_solid;
            this.btn_master.OnIdleState.IconRightImage = global::Project_ACS.res_icons.caret_down_solid;
            this.btn_master.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.btn_master.OnPressedState.BorderRadius = 1;
            this.btn_master.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_master.OnPressedState.BorderThickness = 1;
            this.btn_master.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(16)))), ((int)(((byte)(24)))));
            this.btn_master.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_master.OnPressedState.IconLeftImage = null;
            this.btn_master.OnPressedState.IconRightImage = null;
            this.btn_master.Size = new System.Drawing.Size(200, 39);
            this.btn_master.TabIndex = 14;
            this.btn_master.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_master.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_master.TextMarginLeft = 0;
            this.btn_master.TextPadding = new System.Windows.Forms.Padding(40, 0, 0, 0);
            this.btn_master.UseDefaultRadiusAndThickness = true;
            this.btn_master.Click += new System.EventHandler(this.btn_master_Click);
            // 
            // btn_dashboard
            // 
            this.btn_dashboard.AllowAnimations = true;
            this.btn_dashboard.AllowMouseEffects = true;
            this.btn_dashboard.AllowToggling = false;
            this.btn_dashboard.AnimationSpeed = 200;
            this.btn_dashboard.AutoGenerateColors = false;
            this.btn_dashboard.AutoRoundBorders = false;
            this.btn_dashboard.AutoSizeLeftIcon = true;
            this.btn_dashboard.AutoSizeRightIcon = true;
            this.btn_dashboard.BackColor = System.Drawing.Color.Transparent;
            this.btn_dashboard.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(44)))));
            this.btn_dashboard.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_dashboard.BackgroundImage")));
            this.btn_dashboard.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_dashboard.ButtonText = "Dashboard";
            this.btn_dashboard.ButtonTextMarginLeft = 0;
            this.btn_dashboard.ColorContrastOnClick = 45;
            this.btn_dashboard.ColorContrastOnHover = 45;
            this.btn_dashboard.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btn_dashboard.CustomizableEdges = borderEdges9;
            this.btn_dashboard.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_dashboard.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_dashboard.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_dashboard.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_dashboard.Dock = System.Windows.Forms.DockStyle.Top;
            this.btn_dashboard.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btn_dashboard.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_dashboard.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(220)))), ((int)(((byte)(228)))));
            this.btn_dashboard.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_dashboard.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_dashboard.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_dashboard.IconMarginLeft = 11;
            this.btn_dashboard.IconPadding = 10;
            this.btn_dashboard.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_dashboard.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_dashboard.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_dashboard.IconSize = 25;
            this.btn_dashboard.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_dashboard.IdleBorderRadius = 1;
            this.btn_dashboard.IdleBorderThickness = 1;
            this.btn_dashboard.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(44)))));
            this.btn_dashboard.IdleIconLeftImage = global::Project_ACS.res_icons.home_solid;
            this.btn_dashboard.IdleIconRightImage = null;
            this.btn_dashboard.IndicateFocus = false;
            this.btn_dashboard.Location = new System.Drawing.Point(0, 104);
            this.btn_dashboard.Name = "btn_dashboard";
            this.btn_dashboard.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_dashboard.OnDisabledState.BorderRadius = -1;
            this.btn_dashboard.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_dashboard.OnDisabledState.BorderThickness = -1;
            this.btn_dashboard.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_dashboard.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_dashboard.OnDisabledState.IconLeftImage = null;
            this.btn_dashboard.OnDisabledState.IconRightImage = null;
            this.btn_dashboard.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btn_dashboard.onHoverState.BorderRadius = -1;
            this.btn_dashboard.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_dashboard.onHoverState.BorderThickness = -1;
            this.btn_dashboard.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(75)))));
            this.btn_dashboard.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_dashboard.onHoverState.IconLeftImage = null;
            this.btn_dashboard.onHoverState.IconRightImage = null;
            this.btn_dashboard.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_dashboard.OnIdleState.BorderRadius = -1;
            this.btn_dashboard.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_dashboard.OnIdleState.BorderThickness = -1;
            this.btn_dashboard.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(44)))));
            this.btn_dashboard.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(220)))), ((int)(((byte)(228)))));
            this.btn_dashboard.OnIdleState.IconLeftImage = global::Project_ACS.res_icons.home_solid;
            this.btn_dashboard.OnIdleState.IconRightImage = null;
            this.btn_dashboard.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.btn_dashboard.OnPressedState.BorderRadius = -1;
            this.btn_dashboard.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_dashboard.OnPressedState.BorderThickness = -1;
            this.btn_dashboard.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(16)))), ((int)(((byte)(24)))));
            this.btn_dashboard.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_dashboard.OnPressedState.IconLeftImage = null;
            this.btn_dashboard.OnPressedState.IconRightImage = null;
            this.btn_dashboard.Size = new System.Drawing.Size(200, 39);
            this.btn_dashboard.TabIndex = 11;
            this.btn_dashboard.Tag = "0";
            this.btn_dashboard.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_dashboard.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_dashboard.TextMarginLeft = 0;
            this.btn_dashboard.TextPadding = new System.Windows.Forms.Padding(40, 0, 0, 0);
            this.btn_dashboard.UseDefaultRadiusAndThickness = true;
            this.btn_dashboard.Click += new System.EventHandler(this.buttonPress);
            // 
            // pl_logo
            // 
            this.pl_logo.Dock = System.Windows.Forms.DockStyle.Top;
            this.pl_logo.Location = new System.Drawing.Point(0, 0);
            this.pl_logo.Name = "pl_logo";
            this.pl_logo.Size = new System.Drawing.Size(200, 104);
            this.pl_logo.TabIndex = 10;
            // 
            // pl_main
            // 
            this.pl_main.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pl_main.Location = new System.Drawing.Point(200, 70);
            this.pl_main.Name = "pl_main";
            this.pl_main.Size = new System.Drawing.Size(864, 531);
            this.pl_main.TabIndex = 9;
            // 
            // MainMenu_Master
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1064, 601);
            this.Controls.Add(this.pl_main);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.panel2);
            this.MinimumSize = new System.Drawing.Size(1080, 640);
            this.Name = "MainMenu_Master";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Master Menu";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.MainMenu_Master_FormClosing);
            this.Load += new System.EventHandler(this.MainMenu_Master_Load);
            this.panel1.ResumeLayout(false);
            this.panel2.ResumeLayout(false);
            this.pl_submenu_master.ResumeLayout(false);
            this.pl_submenu_barang.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label lbl_nama;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Panel pl_submenu_master;
        private System.Windows.Forms.Panel pl_submenu_barang;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_inventory_kategori;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_inventory_barang;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_master_inventory;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_master;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_dashboard;
        private System.Windows.Forms.Panel pl_logo;
        private System.Windows.Forms.Panel pl_main;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_master_bp;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_master_akun;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_master_warehouse;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_inventory_merk;
    }
}